config/routes.rb
Compras::Application.routes.draw do
  devise_for :users

  resources :orders

  resources :products

  root :to => "orders#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

    if user.admin?
      can :manage, :all
    else
      can :manage, Order
    end

  end
end

app/models/item.rb
# encoding: UTF-8
# fields: quantity
class Item < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates_presence_of :quantity, :product
  validates_numericality_of :quantity, :only_integer => true, :greater_than => 0

end

app/models/order.rb
# encoding: UTF-8
class Order < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items, :reject_if => proc { |attr| attr[:quantity].blank? }
  
  def total_amount
    items.to_a.sum { |i| i.product.price * i.quantity }
  end
end

app/models/product.rb
# encoding: UTF-8
# fields: name, description, price
class Product < ActiveRecord::Base
  validates_presence_of :name, :price
  validates_numericality_of :price, :greater_than => 0.0
end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def name
    "#{last_name}, #{first_name}"
  end

  def admin?
    admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  check_authorization

end

app/controllers/orders_controller.rb
# encoding: UTF-8
class OrdersController < ApplicationController

  respond_to :html, :xml, :js, :json

#	before_filter :find_order, :except => [:index, :new, :create]
  load_and_authorize_resource

  # GET /orders
  # GET /orders.xml
  def index
		@orders = Order.all
    respond_with(@orders)
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    respond_with @order
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new
    @order.items << Item.new
    respond_with @order
  end

  # GET /orders/1/edit
  def edit
    respond_with @order
  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])
    flash[:notice] = 'Se guardó el nuevo Order.' if @order.save
    respond_with(@order)
  end

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    flash[:notice] = 'Se actualizó el Order.' if @order.update_attributes(params[:order])
    respond_with(@order)
  end

  # DELETE /orders/1.xml
  def destroy
    flash[:notice] = 'Se eliminó el Order.' if @order.destroy
    respond_with(@order)
  end

  protected

  def find_order
    @order = Order.find(params[:id])
  end
end

app/controllers/products_controller.rb
# encoding: UTF-8
class ProductsController < ApplicationController

  respond_to :html, :xml, :js, :json

#	before_filter :find_product, :except => [:index, :new, :create]
	load_and_authorize_resource

  # GET /products
  # GET /products.xml
  def index
		@products = Product.page(params[:page])
    respond_with(@products)
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    respond_with @product
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new
    respond_with @product
  end

  # GET /products/1/edit
  def edit
    respond_with @product
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])
    flash[:notice] = 'Se guardó el nuevo Product.' if @product.save
    respond_with(@product)
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    flash[:notice] = 'Se actualizó el Product.' if @product.update_attributes(params[:product])
    respond_with(@product)
  end

  # DELETE /products/1.xml
  def destroy
    flash[:notice] = 'Se eliminó el Product.' if @product.destroy
    respond_with(@product)
  end

  protected

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def item_with_product(order, product)
    order.items.to_a.find { |i| i.product == product }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_user_info.html.erb
  <div id="user-info">
    <% if user_signed_in? %>
      <%= "Hi! #{current_user.name}" %> | <%= link_to("Bye!", destroy_user_session_path) %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compras</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'cocoon' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render :partial => "layouts/user_info" %>
  <%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Products</h2>
  <div id="product">
    <%= f.fields_for :items do |item| %>
      <%= render 'item_fields', :f => item %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add item', f, :items %>
    </div>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_item_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :name, f.object.product_id.to_i) %>
  </div>
  <div class="fields">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>

  <%= link_to_remove_association "remove item", f %>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Count of products</th>
    <th>Description</th>
    <th>Total amount</th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.items.map{|i| "#{i.quantity} #{i.product.name}" }.to_sentence %></td>
    <td><%= order.description %></td>
    <td><%= number_to_currency order.total_amount %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @order.description %>  
</p>

<p>Items:</p>
<table border="1">
  <thead>
    <tr>
      <td>Name</td>
      <td>Price</td>
      <td>Quantity</td>
    </tr>
  </thead>
  <tbody>
    <% @order.items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.product.price %></td>
        <td><%= item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<p>Total amount: <%= number_to_currency @order.total_amount %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br/>

<%= paginate @products %>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>